CREATE TABLE [dbo].[AspNetUsers] (
    [Id] nvarchar(450) NOT NULL PRIMARY KEY,
    [DisplayUserName] nvarchar(300) NULL,
    [UserName] nvarchar(256) NULL,
    [NormalizedUserName] nvarchar(256) NULL,
    [Email] nvarchar(256) NULL,
    [NormalizedEmail] nvarchar(256) NULL,
    [EmailConfirmed] bit NOT NULL,
    [PasswordHash] nvarchar(max) NULL,
    [SecurityStamp] nvarchar(max) NULL,
    [ConcurrencyStamp] nvarchar(max) NULL,
    [PhoneNumber] nvarchar(max) NULL,
    [PhoneNumberConfirmed] bit NOT NULL,
    [TwoFactorEnabled] bit NOT NULL,
    [LockoutEnd] datetimeoffset NULL,
    [LockoutEnabled] bit NOT NULL,
    [AccessFailedCount] int NOT NULL,
    [CreatedById] INT NOT NULL,
    [CreatedDateTime] DATETIMEOFFSET(7) NOT NULL DEFAULT SYSUTCDATETIME(),
    [LastModifiedById] INT NULL,
    [LastModifiedDateTime] DATETIMEOFFSET(7) NULL,
);