CREATE TABLE [dbo].[Tasks]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Title] NVARCHAR(200) NOT NULL,
    [IsCompleted] BIT NOT NULL DEFAULT 0,
    [CreatedAt] DATETIMEOFFSET(7) NOT NULL DEFAULT SYSUTCDATETIME()
)