CREATE TABLE [dbo].[Tasks]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Title] NVARCHAR(200) NOT NULL,
    [IsCompleted] BIT NOT NULL DEFAULT 0,
    [CreatedById] INT NOT NULL,
    [CreatedDateTime] DATETIMEOFFSET(7) NOT NULL DEFAULT SYSUTCDATETIME(),
    [LastModifiedById] INT NULL,
    [LastModifiedDateTime] DATETIMEOFFSET(7) NULL,
)